"""Ticker bundle helpers for NSE universes.

Bundle sources:
- `NIFTY100` / `NIFTY200`: official Nifty Indices constituent CSVs.
- `SMALLCAP50`: top 50 constituents from the official Nifty Smallcap 250
  ranked by recent traded-value liquidity.
"""

from __future__ import annotations


NIFTY50 = [
    "RELIANCE",
    "HDFCBANK",
    "ICICIBANK",
    "INFY",
    "TCS",
    "BHARTIARTL",
    "ITC",
    "LT",
    "SBIN",
    "KOTAKBANK",
]

NIFTY_NEXT50 = [
    "ABB",
    "ADANIENSOL",
    "ADANIENT",
    "ADANIPORTS",
    "APOLLOHOSP",
    "AXISBANK",
    "BAJAJ-AUTO",
    "BEL",
    "BPCL",
    "DLF",
]

MIDCAP_SAMPLE = [
    "COFORGE",
    "DIXON",
    "HDFCAMC",
    "IRCTC",
    "KPITTECH",
    "LTF",
    "MOTILALOFS",
    "PERSISTENT",
    "POLYCAB",
    "TATACOMM",
]

SECTORS = {
    "Information Technology": ["TCS", "INFY", "HCLTECH"],
    "Financial Services": ["HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK"],
    "Fast Moving Consumer Goods": ["ITC", "BRITANNIA", "HINDUNILVR"],
    "Capital Goods": ["ABB", "LT", "SIEMENS"],
    "Healthcare": ["APOLLOHOSP", "CIPLA", "SUNPHARMA"],
}

NIFTY100 = [
    "ABB",
    "ADANIENSOL",
    "ADANIENT",
    "ADANIGREEN",
    "ADANIPORTS",
    "ADANIPOWER",
    "AMBUJACEM",
    "APOLLOHOSP",
    "ASIANPAINT",
    "DMART",
    "AXISBANK",
    "BAJAJ-AUTO",
    "BAJFINANCE",
    "BAJAJFINSV",
    "BAJAJHLDNG",
    "BAJAJHFL",
    "BANKBARODA",
    "BEL",
    "BPCL",
    "BHARTIARTL",
    "BOSCHLTD",
    "BRITANNIA",
    "CGPOWER",
    "CANBK",
    "CHOLAFIN",
    "CIPLA",
    "COALINDIA",
    "DLF",
    "DIVISLAB",
    "DRREDDY",
    "EICHERMOT",
    "ETERNAL",
    "GAIL",
    "GODREJCP",
    "GRASIM",
    "HCLTECH",
    "HDFCBANK",
    "HDFCLIFE",
    "HAVELLS",
    "HINDALCO",
    "HAL",
    "HINDUNILVR",
    "HINDZINC",
    "HYUNDAI",
    "ICICIBANK",
    "ICICIGI",
    "ITC",
    "INDHOTEL",
    "IOC",
    "IRFC",
    "NAUKRI",
    "INFY",
    "INDIGO",
    "JSWENERGY",
    "JSWSTEEL",
    "JINDALSTEL",
    "JIOFIN",
    "KOTAKBANK",
    "LTM",
    "LT",
    "LICI",
    "LODHA",
    "M&M",
    "MARUTI",
    "MAXHEALTH",
    "MAZDOCK",
    "NTPC",
    "NESTLEIND",
    "ONGC",
    "PIDILITIND",
    "PFC",
    "POWERGRID",
    "PNB",
    "RECLTD",
    "RELIANCE",
    "SBILIFE",
    "MOTHERSON",
    "SHREECEM",
    "SHRIRAMFIN",
    "ENRIN",
    "SIEMENS",
    "SOLARINDS",
    "SBIN",
    "SUNPHARMA",
    "TVSMOTOR",
    "TCS",
    "TATACONSUM",
    "TMPV",
    "TATAPOWER",
    "TATASTEEL",
    "TECHM",
    "TITAN",
    "TORNTPHARM",
    "TRENT",
    "ULTRACEMCO",
    "UNITDSPR",
    "VBL",
    "VEDL",
    "WIPRO",
    "ZYDUSLIFE",
]

NIFTY200_EXTRA = [
    "360ONE",
    "ACC",
    "APLAPOLLO",
    "AUBANK",
    "ATGL",
    "ABCAPITAL",
    "ALKEM",
    "ASHOKLEY",
    "ASTRAL",
    "AUROPHARMA",
    "BSE",
    "BANKINDIA",
    "BDL",
    "BHARATFORG",
    "BHEL",
    "BHARTIHEXA",
    "BIOCON",
    "BLUESTARCO",
    "COCHINSHIP",
    "COFORGE",
    "COLPAL",
    "CONCOR",
    "COROMANDEL",
    "CUMMINSIND",
    "DABUR",
    "DIXON",
    "EXIDEIND",
    "NYKAA",
    "FEDERALBNK",
    "FORTIS",
    "GMRAIRPORT",
    "GLENMARK",
    "GODFRYPHLP",
    "GODREJPROP",
    "HDFCAMC",
    "HEROMOTOCO",
    "HINDPETRO",
    "POWERINDIA",
    "HUDCO",
    "IDFCFIRSTB",
    "IRB",
    "ITCHOTELS",
    "INDIANB",
    "IRCTC",
    "IREDA",
    "IGL",
    "INDUSTOWER",
    "INDUSINDBK",
    "JUBLFOOD",
    "KEI",
    "KPITTECH",
    "KALYANKJIL",
    "LTF",
    "LICHSGFIN",
    "LUPIN",
    "MRF",
    "M&MFIN",
    "MANKIND",
    "MARICO",
    "MFSL",
    "MOTILALOFS",
    "MPHASIS",
    "MUTHOOTFIN",
    "NHPC",
    "NMDC",
    "NTPCGREEN",
    "NATIONALUM",
    "OBEROIRLTY",
    "OIL",
    "PAYTM",
    "OFSS",
    "POLICYBZR",
    "PIIND",
    "PAGEIND",
    "PATANJALI",
    "PERSISTENT",
    "PHOENIXLTD",
    "POLYCAB",
    "PREMIERENE",
    "PRESTIGE",
    "RVNL",
    "SBICARD",
    "SRF",
    "SONACOMS",
    "SAIL",
    "SUPREMEIND",
    "SUZLON",
    "SWIGGY",
    "TATACOMM",
    "TATAELXSI",
    "TATATECH",
    "TORNTPOWER",
    "TIINDIA",
    "UPL",
    "UNIONBANK",
    "VMM",
    "IDEA",
    "VOLTAS",
    "WAAREEENER",
    "YESBANK",
]

SMALLCAP50 = [
    "HINDCOPPER",
    "MCX",
    "NETWEB",
    "TEJASNET",
    "KAYNES",
    "MRPL",
    "DATAPATTNS",
    "GRSE",
    "NEWGEN",
    "IFCI",
    "ANGELONE",
    "FORCEMOT",
    "AMBER",
    "CDSL",
    "GMDCLTD",
    "ENGINERSIN",
    "JINDALSAW",
    "CHENNPETRO",
    "TARIL",
    "LAURUSLABS",
    "OLAELEC",
    "IEX",
    "BANDHANBNK",
    "RBLBANK",
    "JWL",
    "MANAPPURAM",
    "PGEL",
    "REDINGTON",
    "SCI",
    "ANANTRAJ",
    "SAGILITY",
    "NATCOPHARM",
    "NAVINFLUOR",
    "HAPPSTMNDS",
    "HFCL",
    "CREDITACC",
    "HBLENGINE",
    "SAMMAANCAP",
    "RADICO",
    "LTFOODS",
    "ATHERENERG",
    "IIFL",
    "KARURVYSYA",
    "PRAJIND",
    "RPOWER",
    "ITI",
    "INOXWIND",
    "NBCC",
    "SYRMA",
    "JBMA",
]

RS_TOP_100 = [
    "360ONE", "3MINDIA", "ABB", "ACC", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", 
    "ADANIPOWER", "AEGISCHEM", "AETHER", "AFCONS", "AFFLE", "AJANTPHARM", "AKZOINDIA", 
    "ALKYLAMINE", "ALLCARGO", "ALOKINDS", "AMBER", "AMBUJACEM", "ANANDRATHI", "ANANTRAJ", 
    "ANGELONE", "APARINDS", "APLAPOLLO", "APOLLOHOSP", "APOLLOTYRE", "APRAMEYA", "APTECHT", 
    "ARE&M", "ARVIND", "ARVINDFASN", "ASAHIINDIA", "ASHOKLEY", "ASIANPAINT", "ASTERDM", 
    "ASTRAL", "ASTRAZEN", "ATGL", "AUBANK", "AUROPHARMA", "AVANTIFEED", "AWL", "AXISBANK", 
    "BAJAJ-AUTO", "BAJAJCON", "BAJAJELEC", "BAJAJFINSV", "BAJAJHFL", "BAJAJHLDNG", "BAJFINANCE", 
    "BALAMINES", "BALKRISIND", "BALMLAWRIE", "BALRAMCHIN", "BANDHANBNK", "BANKBARODA", 
    "BANKINDIA", "BASF", "BATAINDIA", "BAYERCROP", "BDL", "BEL", "BEML", "BERGEPAINT", 
    "BFINVEST", "BFUTILITIE", "BGRENERGY", "BHARATFORG", "BHARATGEAR", "BHARATRAS", "BHEL", 
    "BHARTIARTL", "BHARTIHEXA", "BIOCON", "BIRLACORPN", "BLS", "BLUESTARCO", "BOMDYEING", 
    "BOSCHLTD", "BPCL", "BRIGADE", "BRITANNIA", "BSE", "BSOFT", "CAMS", "CANBK", "CANFINHOME", 
    "CAPACITE", "CAPLIPOINT", "CARBORUNIV", "CASTROLIND", "CEATLTD", "CENTRALBK", "CENTUM", 
    "CENTURYPLY", "CENTURYTEX", "CERA", "CESC", "CGPOWER"
]

BUNDLES = {
    "QUICK": NIFTY50[:5],
    "STANDARD": NIFTY100,
    "EXTENDED": list(dict.fromkeys(NIFTY100 + NIFTY200_EXTRA + RS_TOP_100)),
    "NIFTY100": NIFTY100,
    "NIFTY200": NIFTY100 + NIFTY200_EXTRA,
    "SMALLCAP": SMALLCAP50,
    "RS_TOP_100": RS_TOP_100,
    "ALL": list(dict.fromkeys(NIFTY50 + NIFTY_NEXT50 + MIDCAP_SAMPLE + NIFTY100 + NIFTY200_EXTRA + SMALLCAP50 + RS_TOP_100)),
    "SECTORS": sorted({ticker for tickers in SECTORS.values() for ticker in tickers}),
}


def get_universe(preset: str) -> list[str]:
    """Return tickers for a named preset."""

    normalized = preset.strip().upper()
    if normalized not in BUNDLES:
        raise ValueError(f"Unsupported universe preset: {preset}")
    return list(BUNDLES[normalized])


def to_yfinance(ticker: str) -> str:
    """Convert an NSE ticker into its yfinance symbol."""

    cleaned = ticker.strip().upper()
    return cleaned if cleaned.endswith(".NS") else f"{cleaned}.NS"


if __name__ == "__main__":
    print({"quick": get_universe("quick"), "symbol": to_yfinance("reliance")})
